[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001707BA2D6D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/d18e63a9a08fd96af379a13b4da8b1bf/url
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001707BA2D370>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/d18e63a9a08fd96af379a13b4da8b1bf/url
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001707BA2DF70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/d18e63a9a08fd96af379a13b4da8b1bf/url